### ISSUE TITLE
xrpl.transaction.get_transaction_from_hash() should take optional min_ledger and max_ledger params

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#191]
The `min_ledger` and `max_ledger` params to the [tx method](https://xrpl.org/tx.html) help to reliably determine the outcome of a transaction. The `get_transaction_from_hash()` helper function should at least take `min_ledger` (it can choose `max_ledger` based on the `LastLedgerSequence`) and use them to more smartly categorize failures:

- Transaction isn't in specified range (`searched_all` is true)
- Server doesn't have sufficient ledger history, which can be further split into more results if you know the server's current max validated ledger:
    - Result isn't final (max_ledger is not yet validated)
    - Server is missing necessary history

**Comment by florent-uzio** [comment]
I have been working on this one and I am waiting to have access rights to push my local branch.
@mvadari fyi
