### ISSUE TITLE
Use @property for Response.is_successful (or just make it an attribute)

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#192]
Can you spot what's wrong with the following code?

```py
prelim_result = xrpl.transaction.submit_transaction_blob(blob, client)
print("Preliminary transaction result:", prelim_result)
if not prelim_result.is_successful:
    exit("Submit failed.")
```

It's not obvious, but `is_successful` is a method, so it'll always evaluate as truthy; you'll _never_ run the `exit()` call here. The correct syntax would've been `if not prelim_result.is_successful()`.

We could make `is_successful` a property using the `@property` decorator, or maybe just evaluate it at the time the model is instantiated. With that change, `result.is_successful` would return the correct boolean value. If someone got it wrong and tried `result.is_successful()` that would raise an error (`TypeError: 'bool' object is not callable`), which is much better than the sneaky "always true" bug from the above example.

**Comment by ledhed2222** [comment]
Closing since we will do the solution described in 202. It doesn't make sense to me that this boolean method should be exposed as a property while many others in our lib would not.
