### ISSUE TITLE
WebSocket client with subscription support

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#193]
One of the most common operations in using the XRP Ledger is waiting for something to happen. The WebSocket interface makes this convenient with subscription streams; it would be great to be able to instantiate a WebSocket client from Python and then [subscribe](https://xrpl.org/subscribe.html) to accounts, ledgers, etc.

**Comment by mvadari** [comment]
This is planned as a part of the next release.

**Comment by N3TC4T** [comment]
@mvadari Just for your information I already built a [websocket library ](https://github.com/N3TC4T/python-xrpl-websocket) for XRPL in python couple of years ago, I'm not sure if you are already build it or working on it, if not please let me know so I can include it to this repository as a pull request. Thanks.
