### ISSUE TITLE
Sugar methods should raise on non-success response.

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#202]
The "sugar" methods in the `xrpl.transaction` module should raise an exception when the server returns a error response rather than just silently returning a Response model object with `is_successful() = False`. (The methods in the `xrpl.account` module already do.) Possibly all responses should do that. 

It's weird and tiresome to have to check is_successful() on every call if you're doing a bunch of calls back to back; I'd rather just put a whole block of calls in a try/except and handle network errors or what-have-you all at once.

```
prelim_result = xrpl.transaction.submit_transaction_blob(signed, client)
print("Preliminary transaction result:", prelim_result)
if not prelim_result.is_successful():
    exit("Submit failed.")
tx_id = prelim_result.result["tx_json"]["hash"]
```

If applied to all responses, this would render #192 moot.

**Comment by ledhed2222** [comment]
i prefer this solution than 192. if we do this, we will need to put the response on the raised error so users can inspect it. that would mean adding another field to the `__init__` of XRPLRequestFailureException to capture the raw response and using it throughout.
