### ISSUE TITLE
Better support for transaction flags

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#204]
Many transactions have specific [flags](https://xrpl.org/transaction-common-fields.html#flags-field) that affect how the transaction works. It's important to be able to set these flags when sending certain types of transactions, and when reading/processing certain types of transactions it's even more important to be able to check them to understand the functionality of the transaction (most importantly, Partial Payments, #196). Preferably, this could be done by setting and getting specific options as booleans by name.

The [map of flags to names I wrote a long time ago](https://github.com/mDuo13/txsplain/blob/master/txsplain.py#L22-L63) is still valid and, I believe, up-to-date (any new transaction types not mentioned there don't have any flags).

Furthermore, any bits in the `Flags` field of a transaction that don't represent defined flags MUST be 0. We should enforce that requirement on transactions too.

At the transaction model level, I think there is no reason to directly expose the flags field if we can expose, say, a dict of flag names to bools instead.

**Comment by mvadari** [comment]
Just to clarify, this is basically what we implemented in xrpl.js, right?
