### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by binaryechoes** [XRPLF/xrpl-py#242]
Hello,

I have a couple of questions related to creating and signing transactions for accounts/wallets which were created by  Ledger Nano or Xumm. Is there a Slack, Telegram, or Discord channel to discuss?

Thanks,
Justin

**Comment by ledhed2222** [comment]
Hi there! We don't have a public forum for this repo at the moment. Please ask your question here!

**Comment by binaryechoes** [comment]
great, thanks. 

if I wanted to interact with a wallet created by XUMM or Ledger Nano S, would I use the family seed (secret) generated by https://secret-numbers-to-family-seed.xumm.dev/ with keypairs.derive_keypair to sign a transaction (OfferCreate)?

thanks again!

**Comment by ledhed2222** [comment]
you don't need to directly use `keypairs.derive_keypair`. In this case, you can do something like the following:

```python
from xrpl.wallet import Wallet
from xrpl.models.transactions import OfferCreate
from xrpl.clients import JsonRpcClient
from xrpl.account import get_next_valid_seq_number
from xrpl.transaction import safe_sign_and_submit_transaction


# the readme has URLs you can use to connect
client = JsonRpcClient(rippled_url)

# here, my_seed is a numeric secret. we don't support
# mnemonic-style secrets yet, IE the ones that look like 
# a series of words.
wallet = Wallet(my_seed, 0)

# now, we want to know what your next account sequence number is
wallet.sequence = get_next_valid_seq_number(wallet.classic_address, client)

# now we're ready to make an offer!
offer_tx = OfferCreate(......)
safe_sign_and_submit_transaction(offer_tx, wallet, client)
```

that should work, more or less. i didn't test this so there might be a typo or something in here. let me know if you have issues

**Comment by zulkarnaenariiq** [comment]
To reduce confusion, these 2 functions' name should be changed to a more accurate name based on their respective functions.

 ```
from xrpl.models.amounts import IssuedCurrencyAmount
from xrpl.models.currencies import IssuedCurrency
     
amount = IssuedCurrencyAmount(currency="USD", issuer="rD9W7ULveavz8qBGM1R5jMgK2QKsEDPQVi", value=buy_usd)
amount = IssuedCurrency(currency="USD", issuer="rD9W7ULveavz8qBGM1R5jMgK2QKsEDPQVi")    
```

Newbies and developers alike may be confused by these 2 functions.

**Comment by zulkarnaenariiq** [comment]
There is little to no liquidity on the native DeX on XRPL's testnet.
(XRP/USD), (XRP/BTC), (XRP/EUR), (XRP/ETH) and so on.

The general point of a testnet is for developers to test their products/applications, since Ripple and XRPL is focused to enhance liquidity usage, it'll be a great add to the testnet and xrpl-py for a USD,BTC,ETH,EUR faucet (Assuming XRPL Labs could implement this via xrpl lab's issuing address)

Add a currency faucet for XRPL and faucet function in **xrpl-py**.

**Comment by zulkarnaenariiq** [comment]
Add a "kill switch" between the code's machine and the rippled node.

This may create a possibility for developers to add an "air-gapped wallet" and perhaps other features.

```
>connect node
>get wallet sequence
>get last ledger sequence
>end connection
>sign transaction
>copy signed transaction
>connect node
>send signed transaction securely
```

Maybe make it in:
xrpl.clients.**end_connection**  , just a suggestion.

**Comment by ledhed2222** [comment]
hey @binaryechoes - are you all good here? will close this issue in a few days if so

**Comment by ledhed2222** [comment]
Closing. Please reopen if you still have questions!
