### ISSUE TITLE
Add a "kill switch" function for clients

### ISSUE THREAD

**Issue by wojakkk** [XRPLF/xrpl-py#260]
Add a "kill switch" between the connection of a machine and a selected rippled node.

This may create a possibility for developers to add an "air-gapped wallet" and perhaps other features.

```
>connect node
>get wallet sequence
>get last ledger sequence
>end connection
>sign transaction
>copy signed transaction
>connect node
>send signed transaction securely
```

Maybe make it in:
xrpl.clients.**end_connection** , just a suggestion.

**Comment by ledhed2222** [comment]
hey @wojakkk, the bundled `JsonRpcClient` does not hold a persistent connection, so there is no need to terminate the connection between requests as you indicate. We will soon be releasing web socket clients in our next release, which do have a persistent connect and which do have an ability to terminate their connection.
