### ISSUE TITLE
Signed Transaction & Reliable Submition, need support

### ISSUE THREAD

**Issue by ghost** [XRPLF/xrpl-py#264]
I'm currently trying to create an airgapped transaction thingy:
![image](https://user-images.githubusercontent.com/84985704/122725158-feee4700-d274-11eb-960f-0a621e6a313c.png)

As you all know, when someone signs a transaction, it'll look something like this:
`Payment(account='AccountGoesHere', transaction_type=<TransactionType.PAYMENT: 'Payment'>, fee='10', sequence=Sequence, account_txn_id=None, flags=0, last_ledger_sequence=Ledger_Sequence, memos=None, signers=None, source_tag=None, signing_pub_key='PubKeySignGoesHere', txn_signature='TransactionSigGoesHere', amount='Amount', destination='DestinationAccount', destination_tag=None, invoice_id=None, paths=None, send_max=None, deliver_min=None)`

I tried doing this:
1. Enter Seed
2. Sign transaction
3. Copy and paste to another code that'll send the signed transaction to XRPL node

But it dint work since, i did this:  ( I know this is a dumb solution, just a showcase on what I tried, *help* )
![image](https://user-images.githubusercontent.com/84985704/122725873-bc793a00-d275-11eb-82f8-607974e1d9de.png)

Does anyone know how I can fix this error of mine, thank you!

**Comment by ledhed2222** [comment]
hey @wojakkk just saw this.

what was the error? i see that your editor doesn't like your syntax, is that the problem you're referencing?

if i'm understanding this correctly, what you want is that given a seed, your Pi machine can sign and submit the payment transaction, is that right?

**Comment by wojakkk** [comment]
Hello @ledhed2222 ,

This is what im trying to do:

Seed -> Raspberry Pi (airgapped) -> Sign transaction -> Signed transaction goes into USB stick -> USB stick goes into a connected machine -> Send signed transaction to XRPL node

**Comment by mvadari** [comment]
I believe your main issue is with the syntax of the `TransactionType` - that line should be removed, since the `Payment` object already has the transaction type. 

Based on your output, I assume you're just copy-pasting the output that is printed. What you should be doing is using the `to_dict` and `from_dict` methods on the `Payment` object. 

Here's some sample code that I think should achieve what you're doing:
On the airgapped machine:
```
d = payment.to_dict()
# copy-paste the dictionary output
```
On the connected machine:
```
# assuming you've copy-pasted the transaction into a dictionary named `d`
payment = Payment.from_dict(d)
```
