### ISSUE TITLE
Async client takes a while to close the connection

### ISSUE THREAD

**Issue by yyolk** [XRPLF/xrpl-py#270]
For example if I run the following script with the `websockets` package within a context manager managing the session, it closes quickly. 

https://gist.github.com/yyolk/42b67ec5f1b1a17e273b5497e9eaad88#file-01__websockets__xrpl_stat_table-py

If I run the same code, with `xrpl-py` which is set up to handle the websocket identically, the websocket does close but it takes a while. 

https://gist.github.com/yyolk/42b67ec5f1b1a17e273b5497e9eaad88#file-02__xrpl-py__xrpl_stat_table-py

My first instinct was to see where there was a difference in how `websockets` handled it and how `xrpl-py` does. For the most part it's identical, following the dunder method for `__aexit__` to `close()` when called from the `AsyncWebsocketClient.__aexit__` https://github.com/XRPLF/xrpl-py/blob/e5bbdf458ad83e6670a4ebf3df63e17fed8b099f/xrpl/asyncio/clients/async_websocket_client.py#L58-L65

It led me to notice a few assert statements in the code that seemed pretty reasonable for conditional checks
https://github.com/XRPLF/xrpl-py/blob/e5bbdf458ad83e6670a4ebf3df63e17fed8b099f/xrpl/asyncio/clients/websocket_base.py#L84-L90

However if I run with `python -O` or in optimized mode, which will drop all `assert` statements, I do see the socket program close as swiftly as the one with `websockets` which I've seen very little difference in it's implementation. The only thing that stuck out to me at first glance was using the convenience of [`asyncio.shield(...)`](https://github.com/aaugustin/websockets/blob/b2a95c45fae19fff0a3473158dd02afe2ca42604/src/websockets/legacy/protocol.py#L671) over [spinning up a background thread](https://github.com/XRPLF/xrpl-py/blob/e5bbdf458ad83e6670a4ebf3df63e17fed8b099f/xrpl/clients/websocket_client.py#L92-L113) and these `assert` statements.

I did a quick search and saw we only had `asserts` in a few places and tried dropping it here: https://github.com/yyolk/xrpl-py/tree/patch-20210705

`-O` command line arg: https://docs.python.org/3/using/cmdline.html#cmdoption-o

**Comment by ledhed2222** [comment]
Would you please quantify the time penalty we have? I'd expect even without the assert statements that we're slower than the base library because we are essentially grafting a synchronous response into websockets so that you can use the any client with our helper functions. That's a penalty I believe we should take.

**Comment by intelliot** [comment]
@yyolk Closing as we don't have enough detail
