### ISSUE TITLE
Definitions is missing sfCookie

### ISSUE THREAD

**Issue by RichardAH** [XRPLF/xrpl-py#276]
https://github.com/XRPLF/xrpl-py/blob/master/xrpl/core/binarycodec/definitions/definitions.json

should contain:

https://github.com/ripple/rippled/blob/7bd5d51e4e4e76a5547051d30b330739618eddb0/src/ripple/protocol/impl/SField.cpp#L153

**Comment by RichardAH** [comment]
ValidatedHash is also missing

**Comment by ledhed2222** [comment]
hey thanks for noting. we'll add these values - although feel free to make a PR yourself if you need this sooner!

**Comment by ledhed2222** [comment]
also - it would help to explain what real-world issues this is causing for you so we know how to prioritize this and when to release a fix @RichardAH :)
