### ISSUE TITLE
Raspberry Pi cant install module

### ISSUE THREAD

**Issue by firefly3582** [XRPLF/xrpl-py#277]
Why can't I install xrpl.py module in Rasbian (Raspberry Pi)?

Error:

**Could not find a version that satisfies the requirement xrpl.py (from versions : )
No matching distribution found for xrpl.py**

How do i fix this issue?

**Comment by mvadari** [comment]
The name of the module is `xrpl-py`, not `xrpl.py`.

**Comment by firefly3582** [comment]
> 
> 
> The name of the module is `xrpl-py`, not `xrpl.py`. Are you able to find that?

LOL, silly mistake of mine, damn I really wasted an hour on this 'error'
