### ISSUE TITLE
Issued Currency Tutorial

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl-py#281]
Hey guys,

I'm trying to follow along the tutorial [here](https://xrpl.org/issue-a-fungible-token.html) and I'm receiving an error when sending the payment tx on step 9.

The error I receive is:

`{'send_max': 'A currency conversion requires a `send_max` value.'}`

I then added send_max as the value/3840. Then I get this error:

`tecPATH_DRY: Path could not send partial amount.`

Here is what the lines are after steps 1 to 8.

COLD:
{'account': 'r9JTgGHEe898ecnhfTm5gULGi9LKXhNgkP', 'balance': '0', 'currency': 'CSC', 'limit': '0', 'limit_peer': '10000000000', 'no_ripple': True, 'no_ripple_peer': False, 'quality_in': 0, 'quality_out': 0}

HOT:
{'account': 'r4WujFh1qwpTaQa2FXFT9gJ4oPo7S6tohb', 'balance': '0', 'currency': 'CSC', 'limit': '10000000000', 'limit_peer': '0', 'no_ripple': False, 'no_ripple_peer': True, 'quality_in': 0, 'quality_out': 0}

Thanks for your help.

**Comment by dangell7** [comment]
It was the send amount, which needed to be represented as an Issued Currency Amount?

```
built_transaction = Payment(
    account=signor,
    amount=IssuedCurrencyAmount(
        currency='CSC',
        issuer=signor,
        value=str(value)
    ),
    destination=address,
    send_max=IssuedCurrencyAmount(
        currency='CSC',
        issuer=signor,
        value=str(value)
    )
)

signed_tx = safe_sign_and_autofill_transaction(
    transaction=built_transaction,
    wallet=Wallet(key, 0),
    client=cls.w3,
)

tx_result = send_reliable_submission(signed_tx, cls.w3)
```

If this is correct I can change the docs? Also, I added the account_lines function and submitted a PR.

**Comment by mvadari** [comment]
I don't quite follow what the issue with the docs is (or why you had that problem). If you take a look at [the Payment docs](https://xrpl.org/payment.html#types-of-payments), just sending an IssuedCurrency payment doesn't require a `send_max`.

**Comment by dangell7** [comment]
I thought I was clear but I can try to explain more. if I remove the send_max, I received the `{'send_max': 'A currency conversion requires a send_max value.'}` error.

**Comment by mvadari** [comment]
Oh sorry, it appears I misread/misremembered the docs. A cross-currency payment _is_ sending issued currency from one person to another, if you take a look at this section: https://xrpl.org/payment.html#types-of-payments.
