### ISSUE TITLE
Instantiate wallet from "secret numbers" (XLS-12)

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-py#305]
The [Secret Numbers standard (XLS-12)](https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-12) defines an alternate format for an account seed or private key, which is used by XUMM wallet and possibly others. The Wallet class should support instantiation from an array or string of secret numbers.

**Comment by JST5000** [comment]
Here's a PR for the same task in xrpl-js which might be useful as a reference - https://github.com/XRPLF/xrpl.js/pull/1799

**Comment by JST5000** [comment]
Completed in the beta release
