### ISSUE TITLE
Cannot delete TrustLine

### ISSUE THREAD

**Issue by roukrak** [XRPLF/xrpl-py#306]
Hello,

I cannot delete my TrustLine XAU/r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH (Ripple Singapore).
This is my tx I sent:

```python
tx = TrustSet(
    account="rG1ZxXD3z8KKekVdxr6iVB3LZKrxGxrCRx",
    limit_amount=IssuedCurrencyAmount(
        currency="XAU",
        issuer="r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH",
        value="0"
    )
)
```

As you can see here https://bithomp.com/explorer/rG1ZxXD3z8KKekVdxr6iVB3LZKrxGxrCRx the transaction succeeded (multiple times) but the trust line is not deleted. It worked for many lines before except for that one. I also do not hold any positive balance for that trust line.

Thanks!

**Comment by mDuo13** [comment]
This is one of the trickiest parts of deleting a trust line: the "No Ripple" state of this trust line is _not in its default state_ so the line can't be deleted.

Your account's "Default Ripple" setting is off (which is normal) which means that "No Ripple **on**" is the default state for your trust lines. However, your No Ripple setting for this trust line is also _off_. The line should automatically be deleted if you send a transaction like this one:

```py
from xrpl.models.transactions import TrustSetFlag
tx = TrustSet(
    account="rG1ZxXD3z8KKekVdxr6iVB3LZKrxGxrCRx",
    limit_amount=IssuedCurrencyAmount(
        currency="XAU",
        issuer="r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH",
        value="0"
    ),
    flags=TrustSetFlag.TF_SET_NO_RIPPLE
)
```

**Comment by roukrak** [comment]
> This is one of the trickiest parts of deleting a trust line: the "No Ripple" state of this trust line is _not in its default state_ so the line can't be deleted.
> 
> Your account's "Default Ripple" setting is off (which is normal) which means that "No Ripple **on**" is the default state for your trust lines. However, your No Ripple setting for this trust line is also _off_. The line should automatically be deleted if you send a transaction like this one:
> 
> ```python
> from xrpl.models.transactions import TrustSetFlag
> tx = TrustSet(
>     account="rG1ZxXD3z8KKekVdxr6iVB3LZKrxGxrCRx",
>     limit_amount=IssuedCurrencyAmount(
>         currency="XAU",
>         issuer="r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH",
>         value="0"
>     ),
>     flags=TrustSetFlag.TF_SET_NO_RIPPLE
> )
> ```

Worked perfectly 👌🏼
Thank you!
