### ISSUE TITLE
Allow users to pay high transaction fees without restriction

### ISSUE THREAD

**Issue by wojake** [XRPLF/xrpl-py#338]
https://github.com/XRPLF/xrpl-py/blob/feab4a0e3a69d4e3a2f355bbb3e67faa73690032/xrpl/asyncio/transaction/main.py#L275-L284

Why would we want to restrict the users from paying high transaction fees?

**Comment by mvadari** [comment]
This is to prevent people from accidentally passing in too high fees. You can turn this off by passing in `check_fee=False` to `safe_sign_and_submit_transaction`.

**Comment by wojake** [comment]
Ah I see, Thank you
