### ISSUE TITLE
How can i black hole an address

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#345]
How can i black hole an address i used to mint a token.

**Comment by mvadari** [comment]
You can black hole an address by setting the RegularKey to one of the black hole accounts and then setting the `lsfDisableMaster` flag on the account.

https://www.xrpchat.com/topic/6810-creating-a-black-hole-locked-account/?do=findComment&comment=65161

**Comment by ObiajuluM** [comment]
thanks
