### ISSUE TITLE
Pagination of AccountNFTs not working?

### ISSUE THREAD

**Issue by drsm79** [XRPLF/xrpl-py#348]
The following code doesn't work:

```
from xrpl.models.requests import AccountNFTs
from xrpl.clients import JsonRpcClient
from xrpl.account import get_account_info

client = JsonRpcClient("http://xls20-sandbox.rippletest.net:51234")
wallet = "rLJoSG7bGNUbVDNzCQpX84GnTdGa5g3cXN"
account_info = get_account_info(wallet, client).result["account_data"]

print(f"Wallet has {account_info.get('MintedTokens', 0)} tokens")

nft_list_rq = AccountNFTs(account=wallet, limit=25)

print(nft_list_rq)
response = client.request(nft_list_rq)
nft_list = response.result.pop("account_nfts")
print(response)
print("returned length", len(nft_list))
```

I would expect the `limit` to result in 25 nfts in nft_list (per https://js.xrpl.org/interfaces/AccountNFTsRequest.html#limit), I also notice it's not getting the marker back to paginate.  Am I using the API wrong or are limits/pagination not implemented yet?

**Comment by drsm79** [comment]
Hmm, playing with this some more by directly invoking the json api, and by lowering the limit, I _think_ the issue is server side not in the client. Has anyone had this work?

**Comment by JST5000** [comment]
I was running into some problems getting this to run locally (Unrelated, I wasn't able to import AccountNFTs, which I think is an environment issue), but there is precedent for the server not being required to honor the value. Ex. `account_lines`'s `limit` field: https://xrpl.org/account_lines.html

**Comment by drsm79** [comment]
Closing this - the issue is subtler/different & not in the client code.
