### ISSUE TITLE
BookOffers request

### ISSUE THREAD

**Issue by rzRea** [XRPLF/xrpl-py#357]
Hello, I just learn how to use python for xrpl.
But i got confused by this simple task.
I want to create a simple script to request.BookOffers.
This is the code that i use,
![IMG-20220216-WA0005](https://user-images.githubusercontent.com/99835728/154342951-285b385e-464c-4229-88c8-990888c2227f.jpg)
And this is what i've got when run it,
![IMG-20220216-WA0006](https://user-images.githubusercontent.com/99835728/154343057-f8284336-4dae-4319-ada9-8b913fb0efdd.jpg)
Can you help me how to fix it?
Thank you in advance.

**Comment by mvadari** [comment]
It should be `taker_pays=XRP()` - `XRP` is a class

**Comment by rzRea** [comment]
> It should be `taker_pays=XRP()` - `XRP` is a class

Thank you so much. It work. Now i can checking price without opening dex.
