### ISSUE TITLE
Cannot convert 1 drop expressed in XRP to drops

### ISSUE THREAD

**Issue by LimpidCrypto** [XRPLF/xrpl-py#360]
I want to convert 0.000001 XRP to drops (=1 drop) with `xrp_to_drops` but it raises the XRPRangeException.
When I increase the amount to 0.000002 XRP it converts the amount to drops correctly.
Also when I am using `drops_to_xrp` to convert one drop to XRP it returns 0.000001 XRP correctly.

**Comment by mvadari** [comment]
This appears to be some sort of bug in `Decimal`:
```py
>>> from decimal import Decimal
>>> one_drop = Decimal("0.000001")
>>> 0.000001 == one_drop
False
>>> 0.000001 < one_drop
True
>>> float(one_drop)
1e-06
>>> float(one_drop) == 0.000001
True
```
It should work if you use `Decimal(0.000001)`

**Comment by LimpidCrypto** [comment]
Yes that works for now. But it seems to be important that you specify that drop as string not float.
Do:
`xrp_to_drops(Decimal("0.000001"))`

Not:
`xrp_to_drops(Decimal(0.000001))`
