### ISSUE TITLE
How do i return an escrow id

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#362]
How do i find an escrow id for canceling or finishing an escrow?

This is what the chain returns when I query it for escrow objects with `Account Object` request.

```
    {
      "Account": "rKvgxFsMgH6LDqsb1iApraZu6cVT7nUM4c",
      "Amount": "100000000",
      "Destination": "rHUDzYZf76A8jbH3wW5PongXjNDn3zACx3",
      "DestinationNode": "0",
      "FinishAfter": 700174827,
      "Flags": 0,
      "LedgerEntryType": "Escrow",
      "OwnerNode": "0",
      "PreviousTxnID": "B28AFC6415DCBE201C22B03A7D25FA8CAA5502093E12CA951085E9812E5D929A",
      "PreviousTxnLgrSeq": 25934092,
      "index": "3E3E872C2D5345E531F8918F1FB39AB5E455CD5F6D5FB529444329B404243353"
    },
```

**Comment by intelliot** [comment]
To [cancel](https://xrpl.org/escrowcancel.html) or [finish an escrow](https://xrpl.org/escrowfinish.html), you need its `OfferSequence`, which is the transaction sequence (or Ticket number) of `EscrowCreate` transaction that created the escrow.

The `PreviousTxnID` is the identifying hash of the transaction that most recently modified this object, which (I believe) for an [escrow](https://xrpl.org/escrow-object.html) should be the `EscrowCreate` transaction.

So in your example, you can look up `B28AFC6415DCBE201C22B03A7D25FA8CAA5502093E12CA951085E9812E5D929A` (e.g. with [tx](https://xrpl.org/tx.html)) and look at the `Sequence` (or `TicketSequence` if Sequence is `0`).

**Comment by ObiajuluM** [comment]
you are awesome

**Comment by ObiajuluM** [comment]
is it the `hash` in this result that I will use to search for the transaction info?

```
"tx": {
      "Account": "rJxS67Wwzt4fcCo2dhH5Nqxze8SARHPMLA",
      "Amount": {
        "currency": "000",
        "issuer": "rJxS67Wwzt4fcCo2dhH5Nqxze8SARHPMLA",
        "value": "3840"
      },
      "Destination": "rhK5YNf4Xh3LQCsyzLMgauomfT862PhevU",
      "Fee": "10",
      "Flags": 0,
      "LastLedgerSequence": 22362510,
      "Sequence": 21983233,
      "SigningPubKey": "EDD4AC18ACBA19A3E9C2243485DCB9010C319B25143BD2B75697FBD1F9C778E65F",
      "TransactionType": "Payment",
      "TxnSignature": "E2617BA1DE7B7C9D7453ACFE1307C6D48E3E7BFB3AD7F73EE6F5510AA40843E5EFC4BA200F6370FA0C5E7BE638F50801FFE6222983F08CCD004A492E47CA780D",
      "date": 689116472,
      "hash": "301583DF77988E3AC5A4985BFA18F97B9D01299FD62C7D609C296428D6A5C9EA",
      "inLedger": 22362492,
      "ledger_index": 22362492
    },
```

**Comment by wojake** [comment]
Yes, you'd be using the tx's hash (under `hash`) to search the full transaction on the ledger.
