### ISSUE TITLE
How do I generate signatures for payment channels

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#376]
How do I generate signatures for payment channels and for escrows, is there an SDK or documentation on how to do this?.
Currently, I use time-locked escrows, I'm trying to experiment with signatures.
Thanks.

**Comment by dangell7** [comment]
https://github.com/XRPLF/xrpl-dev-portal/issues/1055

**Comment by ObiajuluM** [comment]
thanks
