### ISSUE TITLE
How do i check if an asset i am holding has a transfer fee?

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#382]
How do i check if an asset i am holding has a transfer fee?

**Comment by JST5000** [comment]
The answer differs for issued tokens and NFTs.

For issued currencies, TransferFee is a setting on the issuing account. So you can look it up with an `account_info` request pointed to the issuer of the issued currency you're curious about. 
Doc with more details on how this works: https://xrpl.org/transfer-fees.html#transfer-fees
Specifically the part that explains what the number means: https://xrpl.org/transfer-fees.html#technical-details
Easy way to send the `account_info` request online: https://xrpl.org/websocket-api-tool.html#account_info


For NFTs the transfer fee is encoded into the NFTokenID. You can use xrpl.js or xrpl-py to decode it using the `parseNFTokenID` or `parse_nftoken_id` functions respectively. (You can also manually decode it following the logic in XLS-20d copied below for reference :) ) 

000B 0C44 95F14B0E44F78A264E41713C64B5F89242540EE2 BC8B858E 00000D65
+--- +--- +--------------------------------------- +------- +-------
|    |    |                                        |        |
|    |    |                                        |        `---> Sequence: 3,429
|    |    |                                        |
|    |    |                                        `---> Taxon: 146,999,694
|    |    |
|    |    `---> Issuer: rNCFjv8Ek5oDrNiMJ3pw6eLLFtMjZLJnf2
|    |
|    `---> TransferFee: 314.0 bps or 3.140%
|
`---> Flags: 12 -> lsfBurnable, lsfOnlyXRP and lsfTransferable

**Comment by khancode** [comment]
@ObiajuluM Closing this issue. If you have any further questions, feel free to reopen this.
