### ISSUE TITLE
Is it possible to generate a unique address

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#385]
Is it possible to generate a classic address with a unique set of characters without brute force?

by brute force I mean
```
while True:
    wallet = Wallet.create()
    if "earl" in wallet.classic_address:
        print("found")
        print(wallet.classic_address, wallet.seed)
    else: 
        print("not found")
```

if there is any other way please share

**Comment by mvadari** [comment]
https://github.com/WietseWind/xrp-vanity-generator
