### ISSUE TITLE
Confusing exception when defining `AccountSet` transaction

### ISSUE THREAD

**Issue by LimpidCrypto** [XRPLF/xrpl-py#400]
I was just testing what transaction flags are valid with one each other. When trying the combinations `('asf_disallow_xrp', 'asf_global_freeze')`, `('asf_disable_master', 'asf_no_freeze')`, `('asf_deposit_auth', 'asf_require_dest')` and `('asf_default_ripple', 'asf_require_auth')` the following exception gets raised for every combination as soon as I define the `AccountSet` transaction.
```
File "/Users/user/dev/XRPL-trading-bot/xrpl_trading_bot/test.py", line 19, in <module>
    transaction = AccountSet(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/xrpl-trading-bot-gUWitrsl-py3.9/lib/python3.9/site-packages/xrpl/models/utils.py", line 60, in new_init
    original_init(self, **kwargs)
  File "<string>", line 22, in __init__
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/xrpl-trading-bot-gUWitrsl-py3.9/lib/python3.9/site-packages/xrpl/models/base_model.py", line 230, in __post_init__
    self.validate()
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/xrpl-trading-bot-gUWitrsl-py3.9/lib/python3.9/site-packages/xrpl/models/base_model.py", line 241, in validate
    raise XRPLModelException(str(errors))
xrpl.models.exceptions.XRPLModelException: {'nftoken_minter': '                Must be present if AccountSetFlag.ASF_AUTHORIZED_NFTOKEN_MINTER is set'}
```
This is my code:
```python
from itertools import combinations

from xrpl.clients import WebsocketClient
from xrpl.models import AccountSet
from xrpl.models.flags import TX_FLAGS
from xrpl.transaction import (
    safe_sign_and_autofill_transaction,
    send_reliable_submission,
)
from xrpl.wallet import generate_faucet_wallet


txn_type = "AccountSet"
flags = TX_FLAGS[txn_type]
flag_combos = list(combinations(flags, 2))
len_flag_combos = len(flag_combos)
for num, combo in enumerate(flag_combos):
    print(combo)
    with WebsocketClient("wss://s.altnet.rippletest.net/") as client:
        wallet = generate_faucet_wallet(client)
        transaction = AccountSet(
            account=wallet.classic_address,
            set_flag=sum([flags[name] for name in combo]),
        )
        signed_txn = safe_sign_and_autofill_transaction(
            transaction=transaction,
            wallet=wallet,
            client=client
        )
        print(send_reliable_submission(transaction=signed_txn, client=client))
    print(f"{num + 1} of {len_flag_combos}\n")
```
As you can see for every transaction there is a new wallet generated. Can someone please explain to me what the error has to say?

**Comment by mvadari** [comment]
You can only set one flag at a time with the `SetFlag` field. You can't do combos.

For more details: https://xrpl.org/accountset.html#accountset

**Comment by LimpidCrypto** [comment]
> You can only set one flag at a time with the `SetFlag` field. You can't do combos.
> 
> For more details: https://xrpl.org/accountset.html#accountset

But then why could I successfully submit a combo like `('asf_require_auth', 'asf_require_dest')` or `('asf_default_ripple', 'asf_disable_master')` to the Testnet?

**Comment by mvadari** [comment]
> But then why could I successfully submit a combo like `('asf_require_auth', 'asf_require_dest')` or `('asf_default_ripple', 'asf_disable_master')` to the Testnet?

Did you check if the flags were successfully set? My guess is that you actually added one flag that was their sum.

**Comment by LimpidCrypto** [comment]
You are right, but not only that. The network also allows flag sums like 12 (https://testnet.xrpl.org/transactions/97435C360F606AB8C57F95AA40A8E5D6384B181F887925765CFF54BBFDEB9B0B/raw) but 12 does not exist. Wouldn't it make sense to at least limit the fields `flags` and `set_flag` to 10 for the transaction type `AccountSet`?

**Comment by LimpidCrypto** [comment]
Also it should be able to set the `set_flag` field with the same possiblities (`int`, `AccountSetFlag` and `AccountSetFlagInterface`) as `flags`, right? As long as the user then does not provide the flag as `int` we should be able to prevent users to get unexpected results by setting more than one flag at once.

**Comment by mvadari** [comment]
The library doesn't check for every possible error you could make with the models, because it becomes harder to maintain the library the more checks you add.
