### ISSUE TITLE
XRPL asset list

### ISSUE THREAD

**Issue by binaryechoes** [XRPLF/xrpl-py#404]
Hello, 

I'm trying to compile a list of tokens which are available on the XRPL. 

I can't seem to find an API method to answer this question. It seems, I would need to iterate over all accounts on the XRPL and call account_currencies method?  Any suggestions on the best approach? 

Thanks!

**Comment by LimpidCrypto** [comment]
Not really an issue of this library, but you can find a list here: https://xrpl.services/tokens
