### ISSUE TITLE
Add common field `ticket_sequence` to `Transaction`

### ISSUE THREAD

**Issue by LimpidCrypto** [XRPLF/xrpl-py#413]
The field `ticket_sequence` is missing as a common field in the [`Transaction`](https://github.com/XRPLF/xrpl-py/blob/master/xrpl/models/transactions/transaction.py#L243) object. It is needed to specify which ticket to be "replaced" with the transaction.
Since no one complained so far, I guess it's not that urgent.

**Comment by LimpidCrypto** [comment]
I just saw the xrpl.js also does not has the field. Is that intended? Why is that?

**Comment by JST5000** [comment]
I think xrpl.js does have the field here: https://github.com/XRPLF/xrpl.js/blob/aff6988f098ecc033a0cfa7974101f91de5cf948/packages/xrpl/src/models/transactions/common.ts#L156

The xrpl-py missing this value seems like an oversight. Started fixing it but didn't finish today.

**Comment by LimpidCrypto** [comment]
Resolved by #428
