### ISSUE TITLE
BookOffers( ) Method Help

### ISSUE THREAD

**Issue by SirBricksALot** [XRPLF/xrpl-py#494]
BookOffers( ) class / method giving me some heartburn. Code here . . 

`from xrpl.models.requests.book_offers import BookOffers`
`offers = BookOffers(taker_gets='XRP', taker_pays='USD', limit=5)`

response
-------------
('{"id": null, "taker_gets": "XRP", "taker_pays": "USD", "ledger_hash": null, '
 '"ledger_index": null, "limit": 5, "taker": null}')

I'm not getting any actual offers with my code.

I've tried the xrpl.org/book_offers.html which uses the default params below

{"params": [
        {
            "taker": "my_account_here",
            "taker_gets": {
                "currency": "XRP"
            },
            "taker_pays": {
                "currency": "USD",
                "issuer": "rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B"
            },
            "limit": 5
        }
    ]}

Any help greatly appreciated :)

**Comment by mvadari** [comment]
Two things:
* You need to specify the issuer for a non-XRP currency, like it shows in the xrpl.org example. 
* You need to use `Currency` objects for `taker_gets` and `taker_pays`

So something like this:
```py
offers = BookOffers(
    taker_gets=XRP(),
    taker_pays=IssuedCurrency(
        currency='USD',
        issuer='rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B'
    ),
    limit=5
)
```

**Comment by SirBricksALot** [comment]
Thanks for the reply, here's my code :

      try:
          offers = BookOffers(
              taker='<my_xrp_acct_addr_here>',
              taker_gets={'currency':'XRP'},
              taker_pays={'currency':'USD',
                          'issuer':'rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B'},
              limit=5
          )

Here's the response :
 
  ('{"id": null, "taker_gets": {"currency": "XRP"}, "taker_pays":  
{"currency": '
   '"USD", "issuer": "rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B"},  
"ledger_hash": null, '
   '"ledger_index": null, "limit": 5, "taker": '
   '"<my_xrp_acct_addr_here>"}')

So, I'm not seeing and offers, not sure what all is going on?

**Comment by mvadari** [comment]
You'll need to use the currency objects instead of a dictionary.

```py
from xrpl.models import XRP, IssuedCurrency
offers = BookOffers(
  taker='<my_xrp_acct_addr_here>',
  taker_gets=XRP(),
  taker_pays=IssuedCurrency(
    currency='USD',
    issuer='rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B',
  ),
  limit=5
)
```

**Comment by SirBricksALot** [comment]
Ahh yes, that made sense with one minor correction to the import declarations

from xrpl.models.CURRENCIES import XRP, IssuedCurrency

Am still getting output as thus :

BookOffers(method=<RequestMethod.BOOK_OFFERS: 'book_offers'>, id=None,  
taker_gets=XRP(currency='XRP'),  
taker_pays=IssuedCurrency(currency='USD',  
issuer='rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B'), ledger_hash=None,  
ledger_index=None, limit=5, taker='<my_xrp_acct_addr>')

Not sure how to extract the offers (if I was successful)?

**Comment by mvadari** [comment]
Creating a `BookOffers` object just constructs a request, it doesn't actually submit it to the ledger. To do that, you need to create a [client](https://xrpl-py.readthedocs.io/en/stable/source/xrpl.clients.html).

[Here's the example flow](https://xrpl-py.readthedocs.io/en/stable/source/snippets.html#look-up-a-transaction-on-the-ledger) for submitting a `tx` request - the `book_offers` flow is the same.

**Comment by SirBricksALot** [comment]
Excellent! That worked with my final code block here :
  try:
      book = BookOffers(
          taker='<my_xrp_acct_addr>',
          taker_gets=XRP(),
          taker_pays=IssuedCurrency(currency='USD',
              issuer='rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B'),
          limit=5
      )
   
      response = client.request(book)
      offers = response.result
   
      pprint.pprint(offers)

----------------------------------------------

Looks like a steep curve from here to actually being able to link up a  
USD source and transact with an XRP issuer. The XRPL.org knowledge  
base is heavy reading for a noob like me.

  Thank you so much!
