### ISSUE TITLE
`AccountObjectType` is missing `NFT_OFFER`

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl-py#504]
According to xrpl.org, there should be an `AccountOfferType` for NFT_OFFER, but we don't have one currently - https://xrpl.org/account_objects.html#account_objects

Discovered as part of reviewing WoJake's submission here: https://github.com/XRPLF/xrpl-dev-portal/pull/1682

**Comment by wojake** [comment]
https://github.com/XRPLF/xrpl-py/pull/495

**Comment by JST5000** [comment]
Closed because the fix was merged.
