### ISSUE TITLE
Missing parameters for type in Ledger and LedgerData requests

### ISSUE THREAD

**Issue by mmlado** [XRPLF/xrpl-py#532]
According to the documentation for [ledger](https://xrpl.org/ledger.html) and [ledger_data](https://xrpl.org/ledger_data.html) they have a parameter for the request `type`

These parameters are missing from the library. 
- [Ledger class](https://github.com/XRPLF/xrpl-py/blob/master/xrpl/models/requests/ledger.py)
- [LedgerData class](https://github.com/XRPLF/xrpl-py/blob/master/xrpl/models/requests/ledger_data.py)

I've tried modifying the class and just adding the variable, this worked, but then when there is no parameter, it's empty an error is thrown. This might be a reason for missing.

**Comment by rikublock** [comment]
@pdp2121 Do you want a PR for this ? Or is someone already working on this?

**Comment by pdp2121** [comment]
Hi @rikublock, we have added this to our backlog but have not started yet. Please feel free to start on it and let us know! We appreciate your contribution!
