### ISSUE TITLE
Add `nftoken_id`, `nftoken_ids` and `offer_id` meta fields into NFT Tx responses

### ISSUE THREAD

**Issue by ckniffen** [XRPLF/xrpl-py#574]
NFToken transactions have these meta fields being added to a transactions response in rippled@1.11.0. Typing information needs to be added for them.

See: https://github.com/XRPLF/rippled/pull/4447

**Comment by pdp2121** [comment]
This would be parsed into `result` field of `Response`:
`result: Dict[str, Any] = REQUIRED  # type: ignore`

No further action needed here.
