### ISSUE TITLE
Remove support for Python 3.7

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-py#597]
Security support ends in two weeks: https://endoflife.date/python

It will simplify a lot of code, since there are some special imports that are needed for 3.7 support. Some other features added in 3.8 will likely also be useful.

**Comment by justinr1234** [comment]
Aren’t people still struggling just to get off 2? 😅

**Comment by mvadari** [comment]
> Aren’t people still struggling just to get off 2? 😅

It's probably easier to migrate from 3.7 to 3.8, lol. But also, I don't think there's any urgency in this, just opening an issue so it stays on the radar.

**Comment by mvadari** [comment]
This was resolved by #737
