### ISSUE TITLE
[2.0] `classic_address` isn't typed properly

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-py#616]
![image](https://github.com/XRPLF/xrpl-py/assets/8029314/6555aaf0-7336-43d2-b7ff-4fc9f1d32ab5)

It looks like property aliases aren't supported in mypy right now: https://github.com/python/mypy/issues/6700

The best solution is likely to just copy-paste the `address` code, with a `TODO` for when mypy has resolved the issue.

**Comment by JST5000** [comment]
For people encountering this issue before the next release, if you change from `wallet.classic_address` to `.address` the issue goes away.

**Comment by ckniffen** [comment]
Closed by #617
