### ISSUE TITLE
Generate XRP Wallet address using 12 seed phrase

### ISSUE THREAD

**Issue by minhanh1234** [XRPLF/xrpl-py#631]
Does anyone have a python code to generate a XRP wallet address using the a 12 seed phrase?

**Comment by JST5000** [comment]
If you're using a `bip39` encoding (which I believe is also used on the bitcoin network) you may be able to use this library: https://pypi.org/project/bip39/

**Comment by JST5000** [comment]
If you do write that logic, it'd be great to open a PR to the library so we can share it more broadly! Happy to try to answer any questions you have to the best of my ability.

**Comment by JST5000** [comment]
@ckniffen Happened to find a better answer to your question @minhanh1234! - This response by @LimpidCrypto seems to be a way you can resolve your problem I believe: https://github.com/XRPLF/xrpl-py/issues/419#issuecomment-1213204776
