### ISSUE TITLE
Add better error message for inputting `wallet` instead of `wallet.address`

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-py#644]
When someone accidentally creates a transaction object using `account = wallet` instead of `account = wallet.address`, the error is really difficult to debug:
```py
AttributeError: 'Wallet' object has no attribute 'rstrip'
```
A better error message that catches this at the object level (perhaps another validation check) would make this easier to debug.

**Comment by ZiaKhan2008** [comment]
I have been trying to figure this out for hours lol the error it gives is so vauge that I could not even belive that could be an error but you help me man thanks
