### ISSUE TITLE
destination_tag with length of 10 issue

### ISSUE THREAD

**Issue by amirmovafagh** [XRPLF/xrpl-py#675]
Hi, there seems to be an issue with the destination_tag in the xrpl.models.Payment method. When signing the transaction, the following error occurs: 

value_bytes = (value ).to_bytes(_WIDTH, byteorder="big", signed=False) OverflowError: int too big to convert

Is there a way to set the destination_tag length to 10, as exchanges support up to that length?

**Comment by ckniffen** [comment]
What number are you using?  The spec says destination tag is an unsigned integer.  So it should support some numbers with a length of 10 but not all.

**Comment by amirmovafagh** [comment]
> What number are you using? The spec says destination tag is an unsigned integer. So it should support some numbers with a length of 10 but not all.

Yes, you're correct. I made a mistake in generating a 10-digit unsigned integer. Thank you for your response.
