### ISSUE TITLE
lesson1-send-xrp.py returns error on send xrp

### ISSUE THREAD

**Issue by o10222** [XRPLF/xrpl-py#771]
Python3.12 

python3< lesson1-send-xrp.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<stdin>", line 35, in standby_send_xrp
AttributeError: 'str' object has no attribute 'result'

The GUI does not report any errors just the python interpreter.

**Comment by o10222** [comment]
`1964         """Apply first function SUBST to arguments, than FUNC."""
1965         try:
1966             if self.subst:
1967                 args = self.subst(*args)
1968             return self.func(*args)
1969         except SystemExit:
1970             raise
1971         except:
1972             self.widget._report_exception()`

**Comment by mvadari** [comment]
You might want to report this in https://github.com/XRPLF/xrpl-dev-portal/issues instead.

**Comment by anissa-ripple** [comment]
Closing this for now. @o10222 please open an issue in https://github.com/XRPLF/xrpl-dev-portal/issues
